### ISSUE TITLE
Infos is not a word

### ISSUE THREAD

**Issue by psypherium** [xmoto/xmoto#102]
In the menu and in various parts of the code, the word "infos" appears. The word "information" cannot be pluralised, and neither can the shortened form "info".

https://english.stackexchange.com/questions/117552/why-does-information-not-have-a-plural-form
https://ell.stackexchange.com/questions/17748/information-or-informations

I tried searching the code to change the menu from "infos" to "info" but I could not find it, so I'm making this issue instead.

I hope that your day will be good :)

**Comment by Nikekson** [comment]
A large chunk of both the in-game english text and the game's codebase are poorly written in so called "frenglish".
It's become a bit of a pet peeve for me personally :smile: 

You can find the reference english text for this specifically in [``xmoto/GameText.h#L492``](/xmoto/xmoto/blob/20bc4b9de85913ee167733597633f409d3e3c517/src/xmoto/GameText.h#L492).

**Comment by soloturn** [comment]
wiktionary says, while information cannot be counted most of the time, "informations" does exist: https://en.wiktionary.org/wiki/information.

**Comment by psypherium** [comment]
"The legal sense, referring to court filings, is one that does form a plural." Ah, that's interesting.

I guess I should change to saying that the word "information" cannot be pluralised within this context.
