### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [xmoto/xmoto#112]
i've downloaded version 0.6.1. but when selecting it in the macOS Finder it claims to be version '%VERS%'

both the CFBundleVersion and CFBundleShortVersionString entries in your Info.plist file are broken

<img width="256" alt="Screenshot 2021-02-01 at 17 04 42" src="https://user-images.githubusercontent.com/1261954/106484429-e8a34280-64af-11eb-9a20-2404f10f7527.png">
![Uploading Screenshot 2021-02-01 at 17.04.51.png…]()

**Comment by core-code** [comment]
<img width="262" alt="Screenshot 2021-02-01 at 17 04 51" src="https://user-images.githubusercontent.com/1261954/106484477-f1941400-64af-11eb-9b42-09fdad55c6aa.png">

**Comment by Nikekson** [comment]
Fixed by 623948e471e9f8b7d46e75a394a238a1904eafd1

**Comment by core-code** [comment]
awesome, thanks
