### ISSUE TITLE
play via network: crash

### ISSUE THREAD

**Issue by soloturn** [xmoto/xmoto#122]
pressing:
levels - network - connect - play now

and let it run for a couple of seconds, xmoto released version, as well as xmoto compiled from git, crashes with:

```
'xmoto' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Nikekson** [comment]
Could you post a gdb backtrace?

**Comment by soloturn** [comment]
oh, this means for you it works? strange ... when running with the debugger it stalls when printing "downloading ghosts" and the debugger prints, at the end:
```
Thread 1 "xmoto" received signal SIGSEGV, Segmentation fault.
0x000055555584bed8 in XMKey::isPressed(unsigned char*, unsigned char) const ()
```

**Comment by Nikekson** [comment]
Try setting keybinds to their defaults. I'm not sure why, but if you use the same profile between `sdl2` and `master` builds, it still sometimes screws them up.

If that doesn't work, try this patch:
```diff
@@ -433,6 +433,9 @@
 
 bool XMKey::isPressed(Uint8 *i_keystate, Uint8 i_mousestate) const {
   if (m_input == XMK_KEYBOARD) {
+    if (m_keyboard_sym >= SDLK_LAST)
+      return false;
+
     return i_keystate[m_keyboard_sym] == 1;
   }

```

**Comment by soloturn** [comment]
mind doing a release @Nikekson ? can i help?
