### ISSUE TITLE
Updated Swedish translation

### ISSUE THREAD

**Issue by sanchez-gayatri** [xmoto/xmoto#138]
Hello
My name is Sanchez and I have updated the Swedish translation of X-Moto. See the attached po-file. Thanks for your work.

Best regards,
Sanchez

[sv_SE.po.zip](https://github.com/xmoto/xmoto/files/9034600/sv_SE.po.zip)

**Comment by Nikekson** [comment]
Could you open a pull request, or should I commit this under my name?

Also, "mellanslag" should be "backstegstangent"
```po
#: src/xmoto/GameText.h:501
msgid "Press BACKSPACE to return to Checkpoint"
msgstr "Tryck MELLANSLAG för att återvända till Kontrollpunkt"
```

**Comment by sanchez-gayatri** [comment]
You can commit it under your name. Yes, you are right, "mellanslag" should be "backstegstangent". Thanks!
