### ISSUE TITLE
release please ...

### ISSUE THREAD

**Issue by soloturn** [xmoto/xmoto#148]
@Nikekson you would be up to release a new verison?

**Comment by Nikekson** [comment]
There are a few outstanding issues that need to be fixed, but I'll try to push a new release pretty soon

**Comment by limburgher** [comment]
Thank you!

**Comment by Nikekson** [comment]
https://github.com/xmoto/xmoto/releases/tag/v0.6.2

**Comment by limburgher** [comment]
Thank you so much!
