### ISSUE TITLE
Safemode tweaks

### ISSUE THREAD

**Issue by InfinityMin3r** [xmoto/xmoto#149]
When in safe mode a player should only be able to restart on the death screen if a checkpoint hasn't been reached.
This also covers the case of a player in safe mode who is playing a level without checkpoints.

**Comment by Nikekson** [comment]
Does 586374b996f2a60a9ab7c0adaefe2b14ce487e98 fix this properly?

**Comment by InfinityMin3r** [comment]
LGTM!
