### ISSUE TITLE
0.6.2 doesn't start on Windows

### ISSUE THREAD

**Issue by adem4ik** [xmoto/xmoto#156]
**OS:** Windows 10 x64

1. Download [xmoto-0.6.2-win32.zip](https://github.com/xmoto/xmoto/releases/download/v0.6.2/xmoto-0.6.2-win32.zip) or [xmoto-0.6.2-win32-setup.exe](https://github.com/xmoto/xmoto/releases/download/v0.6.2/xmoto-0.6.2-win32-setup.exe)
2. Unzip / install
3. Run xmoto.exe

**Result:** 
![image](https://user-images.githubusercontent.com/4707112/222948791-8164f608-dadf-40c6-a2e6-2ce3830b12a6.png)
`C:\Users\<user>\.config\xmoto\` is empty

**Extra info:** 0.6.1 portable works w/o any problems

**Comment by Nikekson** [comment]
Can confirm, I'll fix it and re-release 0.6.2

**Comment by Nikekson** [comment]
Fixed in d86c88dcd9312e470ba20a717213d5ce2cdf4d6c
