### ISSUE TITLE
`Max framerate` translation won't fit, if it is too long

### ISSUE THREAD

**Issue by adem4ik** [xmoto/xmoto#159]
Version: 0.6.2

1. Switch to Russian
2. Open Options > General > Video

Result: 
![image](https://user-images.githubusercontent.com/4707112/222965847-a5c00a42-5088-451f-96c9-1dc40c31a6cf.png)

P.S. Let me know if I should just make this translation shorter.

**Comment by Nikekson** [comment]
Ideally, the input box's position would depend on the label's width, or it would be placed below it, but that would require bigger changes to the UI code in order to be done properly. I'd suggest just make the translation shorter for now, if possible.

**Comment by adem4ik** [comment]
@Nikekson okey, I'm gonna make it shorter.

**Comment by Nikekson** [comment]
The input box is now positioned based on the label width, and allows for longer translations. There are other elements in the UI that suffer from similar problems, but this is a good enough workaround for now.
