### ISSUE TITLE
UI backgroud has black vertical line

### ISSUE THREAD

**Issue by adem4ik** [xmoto/xmoto#164]
**Version:** 0.6.2
**OS:** Windows 10

1. Set wide resolution (i.e. 1600x900 or 1280x720)
2. Look at the main menu

**Result:** Black vertical line in the middle of the screen

**Extra info:** 0.6.1 had such issue too. It is not reproduceable with 800x600 resolution.

1600x900:
![image](https://user-images.githubusercontent.com/4707112/223479922-a9e30115-3fa0-43c1-848a-03ac5fa58913.png) ![image](https://user-images.githubusercontent.com/4707112/223480040-d47fb914-ca91-468c-8385-aa06d40f688d.png)

800x600:
![image](https://user-images.githubusercontent.com/4707112/223480121-95a5ebd5-f16b-43ef-aa0b-ff27d1b143ee.png)

**Comment by Nikekson** [comment]
This happens because the game draws the background image in 4 separate quadrants (for compatibility with *very* old GPUs) and doesn't align them properly
