### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by louis030195** [xmoto/xmoto#30]
Hey i'm building an [environment](https://github.com/louis030195/xmoto-gym) to train [AI](https://github.com/louis030195/xmoto_learning) to learn to play Xmoto, I wanted to add some features to Xmoto like cli arg to choose the server name the client is connecting by default ...

I tried the steps to build [here](https://wiki.xmoto.tuxfamily.org/index.php?title=Build_for_Unix_(like_GNU/Linux)) but it doesn't seem to be up-to-date ?
Could you give me a direction on how to build from source ? (In my case Ubuntu 18.04 btw)

Thanks !

**Comment by InfinityMin3r** [comment]
[XMOTO-1]

**Comment by Nikekson** [comment]
Build instructions have now been added to:
https://github.com/xmoto/xmoto/wiki/Building-on-Linux
