### ISSUE TITLE
create release tags which can be used for packaging

### ISSUE THREAD

**Issue by soloturn** [xmoto/xmoto#55]
for packaging it would be great if tags would be reachable in the git history. e.g. arch recommends to use "git describe", like here:
* doc, https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function
* some generic examples, https://git.archlinux.org/pacman.git/tree/proto/PKGBUILD-vcs.proto#n33

this then can be used to create a rolling package out of source code:
* https://aur.archlinux.org/packages/xmoto-git/
* with its pkgbuild file: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xmoto-git, in this example it does not include xmoto's version, just the git hash.

**Comment by Nikekson** [comment]
Does the current release fix this?

**Comment by soloturn** [comment]
this works now, thanks! see https://aur.archlinux.org/cgit/aur.git/commit/?h=xmoto-git&id=b320186791f3459685805ec32c9ff148a210a99e
