### ISSUE TITLE
Typos in xmoto.pot

### ISSUE THREAD

**Issue by adem4ik** [xmoto/xmoto#71]
1) Mb it should be "Switch next game mode" - https://github.com/xmoto/xmoto/blob/master/i18n/po/xmoto.pot#L2631 ? 
```
#: src/xmoto/GameText.h:515
msgid "Switch net game mode"
```
2) I believe there should be question mark at the end: "Are you sure you want to delete %i replay?" - https://github.com/xmoto/xmoto/blob/master/i18n/po/xmoto.pot#L297
```
#: src/xmoto/GameText.h:83
#, c-format
msgid "Are you sure you want to delete %i replay"
msgid_plural "Are you sure you want to delete %i replay"
```

**Comment by Nikekson** [comment]
1. It means changing the online game mode, so no typo there
2. Yeah, there should be a question mark there
