### ISSUE TITLE
use lua-5.3?

### ISSUE THREAD

**Issue by soloturn** [xmoto/xmoto#86]
there was a bug report on https://aur.archlinux.org/packages/xmoto saying LC_NUMERIC=de_DE.UTF-8 - which has a comma as decimal separator - causes:
```
$ xmoto 
ODE Message 2: inertia must be positive definite in dMassCheck() [mass.cpp:53]
ODE Message 2: inertia must be positive definite in dMassCheck() [mass.cpp:53]
ODE INTERNAL ERROR 1: assertion "dMassCheck(mass)" failed in dBodySetMass() [ode.cpp:489]
Aborted (core dumped)
```
i could reproduce it with xmoto-0.6.0 using arch linux lua-5.1. i  set -DPREFER_SYSTEM_Lua=OFF to verify, still the same problem. xmoto-git (https://aur.archlinux.org/packages/xmoto-git/) has the lua change from #85, which uses lua-5.3. it works on my system.

is lua really the cause, or using the new version just happens to work around something?

**Comment by Nikekson** [comment]
This is a known bug and has been fixed in [master](/xmoto/xmoto/tree/master) by 831bc02372f8e5bf34ab2f7d3411ade84dc86043.
It's not related to lua, it happens because some standard libc functions like ``atof`` are locale-dependent

**Comment by Nikekson** [comment]
We will push out 0.6.1 soon which will include the fix

**Comment by soloturn** [comment]
hahaha - i love the commit message "code fixes" :)

**Comment by Nikekson** [comment]
I suppose it was bad enough to deserve its own commit - oh well
