### ISSUE TITLE
atoi() call segfault

### ISSUE THREAD

**Issue by Nikekson** [xmoto/xmoto#9]
In [StateMainMenu::updateStats()](https://github.com/xmoto/xmoto/blob/f38ecb277dba9f583b21b1a58b5be1dfb7e997fd/src/states/StateMainMenu.cpp#L880), atoi() is called directly with the result of xmDatabase::getResult(), which can be NULL, causing a segfault. The patch at http://anonscm.debian.org/viewvc/pkg-games/packages/trunk/xmoto/debian/patches/fix_segfault.patch?revision=12926&view=co (against 0.5.9) fixes this.

| | |
|-|-|
| Reported version | 0.5.9 |
| Operating system | All |

**Comment by bb010g** [comment]
Why exactly was this closed? As far as I can tell, it hasn't been fixed yet.
